src/aiscreate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

src/main/urls.py
from django.urls import path
from .views import HomeView, PortfolioView, AboutView

app_name = "main"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('portfolio/', PortfolioView.as_view(), name='portfolio'),
]

src/users/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
]

src/main/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField()
    url = models.URLField(max_length=300)
    skills = models.CharField(max_length=500)
    pub_date = models.DateTimeField()
    img_name = models.CharField(max_length=200)
    image_path = models.CharField(max_length=200, blank=True, default='/')


class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField(blank=False, max_length=250)
    message = models.TextField(blank=False)
    subject = models.TextField(blank=False)

src/users/models.py
from django.contrib.auth.models import AbstractUser, UserManager


class CustomUserManager(UserManager):
    pass


class CustomUser(AbstractUser):
    objects = CustomUserManager()

src/main/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'full_name',
            'email',
            'message',
            'subject'
        ]

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget = forms.TextInput(attrs={
            'placeholder': 'Name',
            'required': True})

        self.fields['email'].widget = forms.EmailInput(attrs={
            'placeholder': 'Email',
            'required': True})

        self.fields['message'].widget = forms.Textarea(attrs={
            'placeholder': 'Message',
            'rows': 6,
            'required': True})

        self.fields['subject'].widget = forms.Textarea(attrs={
            'placeholder': 'Subject',
            'rows': 6,
            'required': True})

src/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

src/main/views.py
from django.views.generic import View
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponseRedirect

from .forms import ContactForm
from .models import Project


class HomeView(View):
    template_name = 'main/main.html'
    form_class = ContactForm

    def get(self, request, *args, **kwargs):
        form = ContactForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            try:
                send_mail(
                    str("AIS {} - {}".format(instance.full_name, instance.subject)),
                    str(instance.message),
                    str(instance.email),
                    [settings.EMAIL_TO],
                    fail_silently=True
                )
                messages.success(request, 'Your message was sent successfully. I will get back to you shortly.')
            except Exception as e:
                print(e)
                messages.error(request, 'Your message has not been sent successfully, please try again later.')
            return HttpResponseRedirect('/#contact')
        return render(request, self.template_name, {'form': form})


class AboutView(View):
    template_name = 'main/about.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class PortfolioView(View):
    template_name = 'main/portfolio.html'

    def get(self, request, *args, **kwargs):
        projects = Project.objects.all()
        for project in projects:
            project.skills = [x for x in str(project.skills).split(',')]
        return render(request, self.template_name, {'projects': projects})

src/users/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

src/main/templates/main/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}
    <section id="portfolio">
        <div class="pfblock" style="padding-bottom:30px; background-color: #74d3e2">
            <div class="offset-lg-2 col-lg-8 wow fadeInUp">
                <h2 class="pfblock-title" style="color: black;">What I can offer</h2>
                <div class="pfblock-line"></div>
                <div class="pfblock-subtitle" style="color: black; text-align: center;">
                    <p>I build websites for personal, e-commerce, business or any other use.</p>
                    <p>I start by talking to you to understand exactly what you want from your site before designing
                        it.</p>
                    <p>Once the plans are drawn up, I hand them over to you and we alter them until you are happy.</p>
                    <p>Whilst making the site, I update you frequently on my progress and let you see what I have
                        achieved.</p>
                    <p>Once you are happy with the site, I will publish it and support it moving forwards.</p>
                </div>
            </div>
        </div>
        <div class="sm-pfblock" style="background-color: #FFFFFF">
            <div class="offset-lg-2 col-lg-8 wow fadeInUp">
                <h2 class="pfblock-title">Background & Experience</h2>
                <div class="pfblock-line"></div>
                <div class="pfblock-subtitle" style="text-align: center;">
                    <p>I set this company up in order to provide software and solutions to clients around the world.</p>
                    <p>Its intention is to create high-end personal and business websites for a great price using
                        templates and pre-designed solutions I have made myself. As the company becomes more established,
                        it has branched out to creating personalised software and mobile apps too.</p>
                    <br><br>
                    <p>On top of my university degree, I have had a large amount of experience creating complex websites
                        for government and business needs with an array of different requirements. Mostly, I have
                        experience with Python and Django frameworks but have worked with a host of different
                        technologies.</p>
                    <p>I have now created and published multiple websites under AIS Software and aim to offer a more
                        personal and friendly experience when building your new website.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/main/templates/main/contact_form.html
{% load crispy_forms_tags %}

<form action="#contact" method="post" id="contact-form">
    <div class="ajax-hidden">
        {% if messages %}
            <ul class="messages" style="list-style-type: none;color: red;text-align:center">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.full_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.email|as_crispy_field }}
            </div>
        </div>
        {{ form.subject|as_crispy_field }}
        {{ form.message|as_crispy_field }}

        <div id="button">
            <input id="submit" class="submit_button btn btn-lg btn-block wow fadeInUp" type="submit" value="SEND"/>
        </div>
    </div>
    <div class="ajax-response"></div>
</form>

src/main/templates/main/main.html
{% extends "base.html" %}
{% load static %}
{% block title %}AISCreate{% endblock %}

{% block content %}
    <section id="mainhome" class="pfblock pfblock-custom-colour">
        <div class="container">
            <div class="row">
                <div class="intro-custom">
                    <div>
                        <h1 class="pfblock-title">Welcome to AISCreate</h1>
                        <div class="pfblock-line pfblock-line-longer"></div>
                        <div class="pfblock-subtitle">
                            <h5 class="start" style="text-align: center">Click on the button to view more</h5>
                        </div>
                    </div>
                    <div style="padding-top: 30px">
                        <a href="{% url 'main:about' %}">
                            <button type="button"
                                    class="btn btn-outline-primary custom-btn-outline grow" style="padding:0;">ABOUT
                            </button>
                        </a>
                        <span style="padding-left: 30px; padding-right: 30px">OR</span>
                        <a href="{% url 'main:portfolio' %}">
                            <button type="button"
                                    class="btn btn-outline-primary custom-btn-outline grow" style="padding:0;">PORTFOLIO
                            </button>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <section id="offer" class="pfblock">
        <div class="row">
            <div class="col-xs-1 col-sm-1 col-lg-1"></div>
            <div class="col-sm-10 col-lg-10">
                <div class="pfblock-header">
                    <h2 class="pfblock-title">What we offer</h2>
                    <div class="pfblock-line"></div>
                    <div class="pfblock-subtitle text-center">
                        <strong style="font-size:larger; font-weight: bold">We create stunning, innovative websites that
                            will make your main and brand stand out.</strong><br>
                        Our personal touch when designing and creating a website ensures you are getting the
                        product you want.
                        <br><br>
                        <ul style="list-style-position: inside;">
                            <li>Start with an initial assessment of what you would like, what you are promoting and how
                                you want to use your site.
                            </li>
                            <li>From there, I will show you a few sites that I have made and you can decide whether you
                                want something similar or more your style.
                            </li>
                            <li>Then let the creating begin!</li>
                            <li>You will get regular updates on the progress and support will be given throughout and
                                after completion!
                            </li>
                        </ul>
                    </div>
                </div>

            </div>

            <div class="col-xs-1 col-sm-1 col-lg-1"></div>

        </div>
    </section>


    <section id="contact" class="pfblock wow fadeInUp" style="background-color: #d2c9c6">
        <div class="row">
            <div class="col-xs-3 col-sm-3 col-lg-3"></div>
            <div class="col-sm-6 col-lg-6">

                <div class="pfblock-header" style="padding-top: 50px">
                    <h2 class="pfblock-title">Contact</h2>
                    <div class="pfblock-line"></div>
                    <div class="pfblock-subtitle text-center">
                        Please fill in the form below with any ideas, requests or questions you have and I'll be happy to respond as quick as I can!
                    </div>
                </div>

            </div>

        </div>

        <div class="row">
            <div class="col-xs-3 col-sm-3 col-lg-3"></div>
            <div class="col-sm-6 col-sm-offset-3  col-lg-6 col-lg-offset-3">
                {% include 'main/contact_form.html' %}
            </div>
            <div class="col-xs-3 col-sm-3 col-lg-3"></div>

        </div>
    </section>
{% endblock %}

src/main/templates/main/portfolio.html
{% extends "base.html" %}
{% load static %}
{% block title %}Portfolio{% endblock %}

{% block content %}
    <section id="portfolio" class="pfblock">
        <div class="container">
            <div class="row" style="padding-top: 100px">
                <div class="col-xs-3 col-sm-3 col-lg-3"></div>
                <div class="col-sm-6 col-lg-6">
                    <div class="pfblock-header wow fadeInUp">
                        <h2 class="pfblock-title">PORTFOLIO</h2>
                        <div style="margin: 10px auto !important;" class="pfblock-line"></div>
                    </div>
                </div>
                <div class="col-xs-3 col-sm-3 col-lg-3"></div>
            </div>

            <div class="row">
                {% for project in projects %}
                    <div class="card col-sm-5 col-lg-5" style="margin-left: 47px;">
                        <div style="width: 100%; height: 30%">
                            <img class="card-img-top" src="{% static project.image_path %}"
                                 style="height: 100%;" alt="{{ project.img_name }}">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ project.title }}</h5>
                            <p class="card-text">
                                {{ project.description }}
                            </p>
                            <h3>Skills Used</h3>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for skill in project.skills %}
                                <li class="list-group-item">{{ skill }}</li>
                            {% endfor %}
                        </ul>
                        <div class="card-body" style="padding-top: 10px">
                            <a href="{{ project.url }}" class="card-link" target="_blank">{{ project.url }}</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

src/templates/base.html
<!doctype html>
<html lang="en">

{% load static %}

{% block head %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="aiscreate">
        <meta name="author" content="Andrew Skea">
        <link rel="icon" href="{% static 'images/logos/logo_no_name.svg' %}">
        {# CSS Styles #}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster|Montserrat|Raleway">
        <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    </head>
{% endblock %}

{% block body %}
    <body>
        <div id="general-classes">
            {% include 'header.html' %}
            <div id="preloader">
                <object id="preloader-logo" type="image/svg+xml"
                        data="{% static 'images/logos/logo_no_name_animated.svg' %}"></object>
            </div>
            {% block content %}
            {% endblock %}
            {% include 'footer.html' %}
        </div>
    </body>
{% endblock %}

{% block scripts %}
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.sticky/1.0.4/jquery.sticky.min.js"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/parallax.min.js' %}"></script>
    <script src="{% static 'js/smoothscroll.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
{% endblock %}

</html>

src/templates/footer.html
<footer id="footer">
    <div class="container">
        <div class="row">

            <div class="col-sm-12">

                <ul class="social-links">
                    <li><a href="https://gitlab.com/AndrewSkea/" class="wow fadeInUp social-link" data-wow-delay=".2s"
                           target="_blank"><i class="fa fa-github"></i></a>GitLab</li>
                    <li><a href="https://github.com/AndrewSkeaIS" class="wow fadeInUp social-link" data-wow-delay=".2s"
                           target="_blank"><i class="fa fa-github"></i></a>Work</li>
                    <li style="color: black"><a href="https://www.linkedin.com/in/andrew-skea-620972115/" class="wow fadeInUp social-link"
                           data-wow-delay=".1s" target="_blank"><i class="fa fa-linkedin"></i></a>.</li>
                    <li style="color: black"><a href="mailto:andrew@aiscreate.com" class="wow fadeInUp social-link"
                           data-wow-delay=".4s"><i class="fa fa-envelope"></i></a>.</li>
                </ul>

                <p class="copyright">Please get in contact through my <a href="/#contact">Contact Form</a>, or
                    <a href="https://www.linkedin.com/in/andrew-skea-620972115/" target="_blank">LinkedIn</a>.</p>


            </div>

        </div>
    </div>
</footer>

src/templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">

    <div class="container">
        <a href="/" class="navbar-left"><img src="{% static 'images/logos/logo_no_name.svg' %}" style="width: 100px; margin-right: 10px"></a>
        <a class="navbar-brand" href="/">AIS CREATE</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/portfolio">Portfolio</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/users/logout">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/users/signup">SignUp</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/users/login">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/users/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock %}

{% block content %}
    <section id="portfolio">
        <div class="pfblock" style="padding-bottom:30px; background-color: #74d3e2">
            <div class="offset-lg-2 col-lg-8 wow fadeInUp">
                <h2 class="pfblock-title" style="color: black;">Sign Up</h2>
                <div class="pfblock-line"></div>
                <div class="pfblock-subtitle" style="color: black; text-align: center;">

                    <form action="#signup" method="post" id="signup-form">
                        <div class="ajax-hidden" style="list-style-type: none;">
                            {% if messages %}
                                <ul class="messages" style="list-style-type: none;color: red;text-align:center">
                                    {% for message in messages %}
                                        <li{% if message.tags %}
                                            class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}

                            {% csrf_token %}
                            {{ form|crispy }}

                            <div id="button">
                                <input id="submit" class="submit_button btn btn-lg btn-block wow fadeInUp" type="submit"
                                       value="Sign Up"/>
                            </div>
                        </div>
                        <div class="ajax-response"></div>
                    </form>

                </div>
            </div>
        </div>

    </section>
{% endblock %}